name: Tests
on: [push]
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: npm install -g yarn && yarn install
      - name: Start Tests
        run: yarn test
